# Семинар 1. Введение в Pandas

На этом семинаре мы познакомимся с библиотекой `pandas`. Она является фактическим стандартом для работы с табличными данными в Python.

Для начала импортируем необходимые библиотеки:

In [4]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

## 1. Загрузка данных

Мы будем работать с датасетом Spotify. Функция `pd.read_csv()` — это основной метод для чтения текстовых файлов с разделителями (обычно запятыми).

Она может принимать огромное количество параметров (например, `sep` для указания разделителя, `index_col` для выбора колонки-индекса), но базово ей достаточно передать путь к файлу или прямую ссылку на него. Pandas сам скачает данные по URL и преобразует их в объект `DataFrame` — двумерную таблицу, похожую на лист Excel.

In [5]:
url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-21/spotify_songs.csv"
df = pd.read_csv(url)

### Метод `.head()` и `.tail()`

Чтобы не выводить всю таблицу (которая может содержать миллионы строк) и не перегружать память, используют методы `.head(n)` и `.tail(n)`.
* `.head()` возвращает первые `n` строк (по умолчанию 5).
* `.tail()` возвращает последние `n` строк.
Это помогает быстро убедиться, что данные загрузились корректно.

In [6]:
df.head()

,track_id,track_name,track_artist,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
0,6f807x0ima9a1j3VPbc7VN,I Don't Care (with Justin Bieber) - Loud Luxur...,Ed Sheeran,66,2oCs0DGTsRO98Gh5ZSl2Cx,I Don't Care (with Justin Bieber) [Loud Luxury...,2019-06-14,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,6,-2.634,1,0.0583,0.1020,0.000000,0.0653,0.518,122.036,194754
1,0r7CVbZTWZgbTCYdfa2P31,Memories - Dillon Francis Remix,Maroon 5,67,63rPSO264uRjW1X5E6cWv6,Memories (Dillon Francis Remix),2019-12-13,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,11,-4.969,1,0.0373,0.0724,0.004210,0.3570,0.693,99.972,162600
2,1z1Hg7Vb0AhHDiEmnDE79l,All the Time - Don Diablo Remix,Zara Larsson,70,1HoSmj2eLcsrR0vE9gThr4,All the Time (Don Diablo Remix),2019-07-05,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,1,-3.432,0,0.0742,0.0794,0.000023,0.1100,0.613,124.008,176616
3,75FpbthrwQmzHlBJLuGdC7,Call You Mine - Keanu Silva Remix,The Chainsmokers,60,1nqYsOef1yKKuGOVchbsk6,Call You Mine - The Remixes,2019-07-19,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,7,-3.778,1,0.1020,0.0287,0.000009,0.2040,0.277,121.956,169093
4,1e8PAfcKUYoKkxPhrHqw4x,Someone You Loved - Future Humans Remix,Lewis Capaldi,69,7m7vv9wlQ4i0LFuJiE2zsQ,Someone You Loved (Future Humans Remix),2019-03-05,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,1,-4.672,1,0.0359,0.0803,0.000000,0.0833,0.725,123.976,189052

## 2. Базовые характеристики датасета

### Атрибут `.shape`
У любого `DataFrame` есть атрибут `.shape`. Обратите внимание: это **атрибут**, а не метод, поэтому он вызывается без круглых скобок в конце. Он возвращает кортеж из двух чисел: `(количество_строк, количество_столбцов)`.

In [7]:
df.shape

(32833, 23)

### Атрибут `.columns`
Тоже атрибут, возвращающий специальный объект (похожий на список) с названиями всех колонок в таблице. Удобно использовать, если колонок много и они не помещаются на экран.

In [9]:
df.columns

Index(['track_id', 'track_name', 'track_artist', 'track_popularity',
       'track_album_id', 'track_album_name', 'track_album_release_date',
       'playlist_name', 'playlist_id', 'playlist_genre', 'playlist_subgenre',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'duration_ms'],
      dtype='object')

### Метод `.info()`
Этот метод выдает «паспорт» датасета. Что мы из него узнаем:
1. Индексы датасета (сколько всего записей).
2. Название каждой колонки.
3. Количество Non-Null (непустых) значений в каждой колонке. Сразу видно, где есть пропуски.
4. Тип данных (Dtype) каждой колонки (например, `int64` — целые числа, `float64` — дробные, `object` — строки).
5. Объем оперативной памяти, который занимает таблица.

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32833 entries, 0 to 32832
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   track_id                  32833 non-null  object
 1   track_name                32828 non-null  object
 2   track_artist              32828 non-null  object
 3   track_popularity          32833 non-null  int64
 4   track_album_id            32833 non-null  object
 5   track_album_name          32828 non-null  object
 6   track_album_release_date  32833 non-null  object
 7   playlist_name             32833 non-null  object
 8   playlist_id               32833 non-null  object
 9   playlist_genre            32833 non-null  object
 10  playlist_subgenre         32833 non-null  object
 11  danceability              32833 non-null  float64
 12  energy                    32833 non-null  float64
 13  key                       32833 non-null  int64
 14  loudness                  32833 non-null  float64
 15  mode                      32833 non-null  int64
 16  speechiness               32833 non-null  float64
 17  acousticness              32833 non-null  float64
 18  instrumentalness          32833 non-null  float64
 19  liveness                  32833 non-null  float64
 20  valence                   32833 non-null  float64
 21  tempo                     32833 non-null  float64
 22  duration_ms               32833 non-null  int64
dtypes: float64(9), int64(4), object(10)
memory usage: 5.8+ MB

### Метод `.describe()`
Генерирует описательную статистику. По умолчанию он берет только **числовые** колонки и считает для них:
- `count` (количество непустых),
- `mean` (среднее арифметическое),
- `std` (стандартное отклонение, разброс),
- `min` и `max`,
- `25%`, `50%` (медиана), `75%` — квантили.

In [11]:
df.describe()

,track_popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
count,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000
mean,42.477081,0.654850,0.698619,5.374471,-6.719499,0.565711,0.107068,0.175334,0.084747,0.190176,0.510561,120.881132,225799.811622
std,24.984074,0.145085,0.180910,3.611657,2.988436,0.495671,0.101314,0.219633,0.224230,0.154317,0.233146,26.903624,59834.006182
min,0.000000,0.000000,0.000175,0.000000,-46.448000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4000.000000
25%,24.000000,0.563000,0.581000,2.000000,-8.171000,0.000000,0.041000,0.015100,0.000000,0.092700,0.331000,99.960000,187819.000000
50%,45.000000,0.672000,0.721000,6.000000,-6.166000,1.000000,0.062500,0.080400,0.000016,0.127000,0.512000,121.984000,216000.000000
75%,62.000000,0.761000,0.840000,9.000000,-4.645000,1.000000,0.132000,0.255000,0.004830,0.248000,0.693000,133.918000,253585.000000
max,100.000000,0.983000,1.000000,11.000000,1.275000,1.000000,0.918000,0.994000,0.994000,0.996000,0.991000,239.440000,517810.000000

## 3. Индексация и выбор данных

Обращение к одной колонке происходит через квадратные скобки по ее названию. В результате мы получаем не DataFrame, а объект типа **Series** (одномерный массив с индексами).

In [12]:
df['track_name'].head()

0    I Don't Care (with Justin Bieber) - Loud Luxur...
1                      Memories - Dillon Francis Remix
2                      All the Time - Don Diablo Remix
3                    Call You Mine - Keanu Silva Remix
4              Someone You Loved - Future Humans Remix
Name: track_name, dtype: object

Если нужно выбрать сразу несколько колонок, мы передаем в квадратные скобки **список** их названий. Обратите внимание на двойные скобки `[[...]]`: внешние — для индексации датафрейма, внутренние — это сам список строк.

In [17]:
ds = df[['track_id', 'track_name', 'track_artist', 'track_popularity',
       'track_album_id', 'track_album_name', 'track_album_release_date',
       'playlist_name', 'playlist_id', 'playlist_genre', 'playlist_subgenre',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'acousticness', 'liveness', 'valence', 'tempo',
       'duration_ms']].head()
ds

,track_id,track_name,track_artist,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,energy,key,loudness,mode,speechiness,acousticness,liveness,valence,tempo,duration_ms
0,6f807x0ima9a1j3VPbc7VN,I Don't Care (with Justin Bieber) - Loud Luxur...,Ed Sheeran,66,2oCs0DGTsRO98Gh5ZSl2Cx,I Don't Care (with Justin Bieber) [Loud Luxury...,2019-06-14,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,0.916,6,-2.634,1,0.0583,0.1020,0.0653,0.518,122.036,194754
1,0r7CVbZTWZgbTCYdfa2P31,Memories - Dillon Francis Remix,Maroon 5,67,63rPSO264uRjW1X5E6cWv6,Memories (Dillon Francis Remix),2019-12-13,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,0.815,11,-4.969,1,0.0373,0.0724,0.3570,0.693,99.972,162600
2,1z1Hg7Vb0AhHDiEmnDE79l,All the Time - Don Diablo Remix,Zara Larsson,70,1HoSmj2eLcsrR0vE9gThr4,All the Time (Don Diablo Remix),2019-07-05,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,0.931,1,-3.432,0,0.0742,0.0794,0.1100,0.613,124.008,176616
3,75FpbthrwQmzHlBJLuGdC7,Call You Mine - Keanu Silva Remix,The Chainsmokers,60,1nqYsOef1yKKuGOVchbsk6,Call You Mine - The Remixes,2019-07-19,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,0.930,7,-3.778,1,0.1020,0.0287,0.2040,0.277,121.956,169093
4,1e8PAfcKUYoKkxPhrHqw4x,Someone You Loved - Future Humans Remix,Lewis Capaldi,69,7m7vv9wlQ4i0LFuJiE2zsQ,Someone You Loved (Future Humans Remix),2019-03-05,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,0.833,1,-4.672,1,0.0359,0.0803,0.0833,0.725,123.976,189052

### `.loc` и `.iloc`

Это два главных свойства для продвинутой индексации:
* `.iloc` (integer location) — ищет по **порядковому номеру** (от 0 до n-1). Работает ровно так же, как стандартные срезы в Python. *Правая граница не включается*.
* `.loc` (location) — ищет по **метке** (имени индекса/колонки). Важнейшее отличие от обычного Python: при использовании срезов через `.loc` *правая граница ВКЛЮЧАЕТСЯ* в результат.

In [18]:
# .iloc: выбираем строки с 10 по 14 (15-я не включится)
df.iloc[10:15]

,track_id,track_name,track_artist,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
10,3eFJI470ALf1EYjywPRsJy,Cross Me (feat. Chance the Rapper & PnB Rock) ...,Ed Sheeran,58,49bXZtlI5kQSqQMSCnSaWO,Cross Me (feat. Chance the Rapper & PnB Rock) ...,2019-06-21,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,6,-6.500,1,0.1810,0.14600,0.000005,0.1240,0.752,121.984,207894
11,3iJeF2izF1QcpCgUc97BLl,Hate Me - R3HAB Remix,Ellie Goulding,67,6e6RVFWdZaoTiLAZOCMnps,Hate Me (R3HAB Remix),2019-08-16,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,8,-4.918,1,0.0554,0.14800,0.000000,0.1330,0.329,123.125,203733
12,6e0CvGZf7CouOpYF8toXHC,Body On My,Loud Luxury,67,2R66I0nzp3NnuUlzIGWQ5P,Body On My,2019-03-29,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,1,-4.675,1,0.0463,0.03990,0.000000,0.3740,0.687,121.985,192507
13,3eLdNmnRWr9gIyBcqTSSti,SOS - Laidback Luke Tribute Remix / Radio Edit,Avicii,68,7Al4TIo0c5twNLfdOh1y1u,SOS (Laidback Luke Tribute Remix),2019-05-17,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,5,-4.451,0,0.0625,0.01110,0.000000,0.3390,0.678,123.919,164516
14,55nMnifaQWKe3f9cbwOXwx,Summer Days (feat. Macklemore & Patrick Stump ...,Martin Garrix,63,2vx3BtBMn8Ed3ygEg1OT2t,Summer Days (feat. Macklemore & Patrick Stump ...,2019-07-12,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,5,-4.446,0,0.0594,0.00733,0.001830,0.0729,0.238,126.070,255238

In [20]:
# .loc: выбираем строки с индексами от 10 до 14 ВКЛЮЧИТЕЛЬНО,
# и указываем конкретные колонки
df.loc[10:14, ['track_name', 'track_popularity']]

                                           track_name  track_popularity
10  Cross Me (feat. Chance the Rapper & PnB Rock) ...                58
11                              Hate Me - R3HAB Remix                67
12                                         Body On My                67
13     SOS - Laidback Luke Tribute Remix / Radio Edit                68
14  Summer Days (feat. Macklemore & Patrick Stump ...                63

## 4. Логическое индексирование (Фильтрация)

В Pandas фильтрация работает через «булевы маски». Выражение вида `df['track_popularity'] > 95` возвращает не сами строки, а объект Series из True/False для каждой строки. Передавая эту «маску» в `df[...]`, мы оставляем только те строки, где стоит True.

In [21]:
# Треки с популярностью больше 95
df[df['track_popularity'] > 95].head()

,track_id,track_name,track_artist,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
139,6cy3ki60hLwimwIje7tALf,RITMO (Bad Boys For Life),The Black Eyed Peas,96,6EobpC5SDFy5DF50dWNVGF,RITMO (Bad Boys For Life),2019-10-12,Dance Pop,37i9dQZF1DWZQaaqNMbbXa,pop,...,10,-7.037,0,0.0657,0.03340,0.000840,0.2370,0.667,104.994,221714
687,7k4t7uLgtOxPwTpFmtJNTY,Tusa,KAROL G,98,7mKevNHhVnZER3BLgI8O4F,Tusa,2019-11-07,Todo Éxitos,2ji5tRQVfnhaX1w9FhmSzk,pop,...,2,-3.280,1,0.2980,0.29500,0.000134,0.0574,0.574,101.085,200960
689,3ZCTVFBt2Brf31RLEnCkWJ,everything i wanted,Billie Eilish,97,4i3rAwPw7Ln2YrKDusaWyT,everything i wanted,2019-11-13,Todo Éxitos,2ji5tRQVfnhaX1w9FhmSzk,pop,...,6,-14.454,0,0.0994,0.90200,0.657000,0.1060,0.243,120.006,245426
711,2b8fOow8UzyDFAE27YhOZM,Memories,Maroon 5,98,3nR9B40hYLKLcR0Eph3Goc,Memories,2019-09-20,Todo Éxitos,2ji5tRQVfnhaX1w9FhmSzk,pop,...,11,-7.209,1,0.0546,0.83700,0.000000,0.0822,0.575,91.019,189486
716,0sf12qNH5qcw8qpgymFOqD,Blinding Lights,The Weeknd,98,2ZfHkwHuoAZrlz7RMj0PDz,Blinding Lights,2019-11-29,Todo Éxitos,2ji5tRQVfnhaX1w9FhmSzk,pop,...,1,-4.075,1,0.0629,0.00147,0.000209,0.0938,0.345,171.017,201573

### Сложные условия
Если нужно несколько условий, обычные `and` и `or` в Python не сработают (они пытаются оценить весь массив целиком, что вызывает ошибку `ValueError`).
Вместо них используются побитовые операторы:
* `&` (логическое И)
* `|` (логическое ИЛИ)
* `~` (логическое отрицание НЕ)

**Важно:** каждое условие обязательно нужно оборачивать в круглые скобки `()`, так как приоритет побитовых операторов выше, чем у операторов сравнения (`>`, `<` и т.д.).

In [22]:
df[(df['playlist_genre'] == 'pop') | (df['danceability'] > 0.9)].head()

,track_id,track_name,track_artist,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
94,2b1BwUGGyKq0CoJd8G1B6M,Harder,Jax Jones,62,1fYOToOfdZXY5hrOra8z2Z,Snacks,2019-07-12,Dance Pop,37i9dQZF1DWZQaaqNMbbXa,pop,...,5,-3.004,0,0.0718,0.0909,0.000000,0.1520,0.751,104.030,159753
171,5gwLIRjGFf3hXuHoKEsWLg,No Goodbye,Paul Kalkbrenner,65,1ix4O6SU7i8W2H6RYb3O8R,No Goodbye,2019-07-26,Dance Room,37i9dQZF1DX2ENAPP1Tyed,pop,...,6,-7.649,0,0.0440,0.0955,0.341000,0.1470,0.626,124.996,168547
186,6j8eH9frh703HaGBaSRS6u,Not in Control,Glaceo,53,5oePvMoJsFArZDomjsTzlk,Not in Control,2019-12-20,Dance Room,37i9dQZF1DX2ENAPP1Tyed,pop,...,0,-5.545,1,0.0958,0.2030,0.000266,0.1630,0.492,121.995,179016
806,3XVozq1aeqsJwpXrEZrDJ9,Ice Ice Baby,Vanilla Ice,70,20O6lfaDAoMhUj5TAvVbb6,Vanilla Ice Is Back! - Hip Hop Classics,2008-11-04,90s Dance Hits,50cXvxgMGrvoUeLhkzCyIO,pop,...,2,-2.784,1,0.0388,0.0025,0.000008,0.1020,0.583,116.012,254467
1062,1CT1dgsDKm4n0ykVyoBj3R,Overflow(変身),YonYon,34,4f9KHk8Eit99Y83Ui4gLtZ,Overflow(変身),2019-03-21,Best of 2019 Dance Pop: Japan,37i9dQZF1DXdOtZGKonFlM,pop,...,6,-5.362,1,0.0483,0.2960,0.001590,0.0469,0.659,120.001,240988

In [45]:
df[(df['track_artist'] == 'Ed Sheeran') & (df['track_popularity'] > 85)][['track_name', 'track_popularity']].shape

ds = df[(df['track_artist'] == 'Ed Sheeran') & (df['track_popularity'] > 85)]
ds[df['track_name'] == 'Shape of You']

,track_id,track_name,track_artist,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
1218,7qiZfU4dY1lWllzX7mPBI3,Shape of You,Ed Sheeran,86,3T4tUhGYeRNVUGevb0wThu,÷ (Deluxe),2017-03-03,Pop Inglés (2020 - 2010s)💙 Música En Inglés 2010s,4QAzO1Z92yqqD6Mf3mOANu,pop,...,1,-3.183,0,0.0802,0.581,0.0,0.0931,0.931,95.977,233713
2317,7qiZfU4dY1lWllzX7mPBI3,Shape of You,Ed Sheeran,86,3T4tUhGYeRNVUGevb0wThu,÷ (Deluxe),2017-03-03,post teen pop,6rjxP7GQKoqqgoakzxl3PY,pop,...,1,-3.183,0,0.0802,0.581,0.0,0.0931,0.931,95.977,233713
2838,7qiZfU4dY1lWllzX7mPBI3,Shape of You,Ed Sheeran,86,3T4tUhGYeRNVUGevb0wThu,÷ (Deluxe),2017-03-03,ElectroPop 2020,4frhr6RQM2fMOm2mpvOVo6,pop,...,1,-3.183,0,0.0802,0.581,0.0,0.0931,0.931,95.977,233713
23899,7qiZfU4dY1lWllzX7mPBI3,Shape of You,Ed Sheeran,86,3T4tUhGYeRNVUGevb0wThu,÷ (Deluxe),2017-03-03,Today's Hits (Clean),7ENISpOJhocpMJVcGb0qcT,r&b,...,1,-3.183,0,0.0802,0.581,0.0,0.0931,0.931,95.977,233713
30406,7qiZfU4dY1lWllzX7mPBI3,Shape of You,Ed Sheeran,86,3T4tUhGYeRNVUGevb0wThu,÷ (Deluxe),2017-03-03,2010 - 2011 - 2012 - 2013 - 2014 - 2015 - 2016...,2DjIfVDXGYDgRxw7IJTKVb,edm,...,1,-3.183,0,0.0802,0.581,0.0,0.0931,0.931,95.977,233713

**Задание 1.** Найдите все треки артиста "Ed Sheeran", популярность которых строго больше 85. Выведите только названия треков и их популярность.

## 5. Группировка данных (.groupby)

Группировка (`.groupby`) реализует концепцию **Split-Apply-Combine**:
1. **Split**: таблица разбивается на куски (группы) по уникальным значениям выбранного столбца.
2. **Apply**: к каждому куску применяется агрегирующая функция (среднее, сумма, минимум и т.д.).
3. **Combine**: результаты склеиваются в новую таблицу, где индексами становятся уникальные значения столбца, по которому мы группировали.

Например, сгруппируем по жанру и посмотрим среднюю популярность:

In [56]:
df.groupby('playlist_genre')['track_popularity'].mean().sort_values(ascending=True).tail(3)

playlist_genre
rap      43.215454
latin    47.026576
pop      47.744870
Name: track_popularity, dtype: float64

### Метод `.agg()`
Часто нужно посчитать не одну метрику, а сразу несколько, причем для разных колонок — разные функции. Метод `.agg()` принимает словарь, где ключи — это названия колонок, а значения — функции (в виде строк или списков строк), которые нужно к ним применить.

In [58]:
df.groupby('playlist_genre').agg({
    'track_popularity': ['mean', 'count'],
    'danceability': 'mean',
    'tempo': 'median'
})

               track_popularity       danceability     tempo
                           mean count         mean    median
playlist_genre
edm                   34.833526  6043     0.655041  127.0560
latin                 47.026576  5155     0.713287  110.9620
pop                   47.744870  5507     0.639302  120.0170
r&b                   41.223532  5431     0.670179  108.7440
rap                   43.215454  5746     0.718353  119.9875
rock                  41.728338  4951     0.520548  124.0350

**Задание 2.** Сгруппируйте датасет по поджанру (`playlist_subgenre`). Для каждого поджанра найдите максимальную энергичность (`energy`) и минимальную акустичность (`acousticness`). Отсортируйте результат по убыванию максимальной энергичности.

In [62]:
df.groupby('playlist_subgenre').agg({
    'energy': 'max',
    'acousticness': 'min'
}).sort_values(by='energy', ascending=False)

                           energy  acousticness
playlist_subgenre
tropical                    1.000      0.000082
dance pop                   0.999      0.000051
trap                        0.999      0.000032
electropop                  0.999      0.000002
big room                    0.998      0.000025
album rock                  0.998      0.000000
hard rock                   0.997      0.000001
electro house               0.997      0.000003
latin hip hop               0.997      0.000036
progressive electro house   0.997      0.000018
pop edm                     0.995      0.000016
latin pop                   0.995      0.000247
urban contemporary          0.995      0.000066
permanent wave              0.994      0.000001
southern hip hop            0.994      0.000002
classic rock                0.993      0.000004
reggaeton                   0.993      0.000443
hip pop                     0.993      0.000051
new jack swing              0.993      0.000105
neo soul                    0.993      0.000025
indie poptimism             0.991      0.000004
post-teen pop               0.988      0.000004
gangster rap                0.987      0.000017
hip hop                     0.986      0.000002

## 6. Создание признаков и метод `.apply()`

Мы можем легко создавать новые колонки, используя арифметические операции над старыми. Это называется векторизованными операциями — pandas применяет математику сразу ко всему столбцу, не используя циклы (что очень быстро).

In [63]:
# Переводим миллисекунды в минуты
df['duration_min'] = df['duration_ms'] / 60000
df[['track_name', 'duration_ms', 'duration_min']].head()

,track_name,duration_ms,duration_min
0,I Don't Care (with Justin Bieber) - Loud Luxur...,194754,3.245900
1,Memories - Dillon Francis Remix,162600,2.710000
2,All the Time - Don Diablo Remix,176616,2.943600
3,Call You Mine - Keanu Silva Remix,169093,2.818217
4,Someone You Loved - Future Humans Remix,189052,3.150867

Если логика сложная и обычными арифметическими операциями не обойтись, мы пишем свою Python-функцию и применяем её к колонке с помощью `.apply()`.

Метод `.apply()` проходит по каждой ячейке в колонке, передает ее значение в функцию и записывает результат в новую ячейку. Часто `.apply()` используют в связке с анонимными лямбда-функциями (`lambda x: ...`), но для читаемости можно передавать и обычные `def`.

In [66]:
def get_popularity_status(pop):
    if pop > 80:
        return 'Hit'
    elif pop > 50:
        return 'Average'
    else:
        return 'Low'

df['popularity_status'] = df['track_popularity'].apply(get_popularity_status)

# Метод .value_counts() считает количество каждого уникального значения в столбце
df['popularity_status'].value_counts()

popularity_status
Low        18866
Average    12622
Hit         1340
Name: count, dtype: int64

## 7. Пропущенные значения (NaN)

В реальных датасетах всегда есть пропуски (NaN - Not a Number).
Метод `.isna()` (или его синоним `.isnull()`) возвращает DataFrame такого же размера, но состоящий из True/False, где True стоит на месте пропуска.

Если применить к этому результату `.sum()`, pandas сложит True (считая их за 1) по каждой колонке и покажет общее число пропусков.

In [ ]:
df.isna().sum()

track_id                    0
track_name                  5
track_artist                5
track_popularity            0
track_album_id              0
track_album_name            5
track_album_release_date    0
playlist_name               0
playlist_id                 0
playlist_genre              0
playlist_subgenre           0
danceability                0
energy                      0
key                         0
loudness                    0
mode                        0
speechiness                 0
acousticness                0
instrumentalness            0
liveness                    0
valence                     0
tempo                       0
duration_ms                 0
duration_min                0
popularity_status           0
dtype: int64

### Метод `.dropna()` и `.fillna()`
Есть два основных пути работы с пропусками:
1. Заполнить их чем-то осмысленным с помощью `.fillna(значение)` (например, нулями или средним).
2. Выбросить строки с пропусками с помощью `.dropna()`.

В нашем случае пропусков всего по 5 штук в трех текстовых колонках при общем объеме в 32000 строк. Потерять 5 строк — не страшно, поэтому смело дропаем.

In [64]:
df = df.dropna()
df.isna().sum()

track_id                    0
track_name                  0
track_artist                0
track_popularity            0
track_album_id              0
track_album_name            0
track_album_release_date    0
playlist_name               0
playlist_id                 0
playlist_genre              0
playlist_subgenre           0
danceability                0
energy                      0
key                         0
loudness                    0
mode                        0
speechiness                 0
acousticness                0
instrumentalness            0
liveness                    0
valence                     0
tempo                       0
duration_ms                 0
track_popularity2           0
duration_min                0
dtype: int64

**Задание 3.** Узнайте, какой исполнитель (`track_artist`) выпустил больше всего треков в статусе 'Hit' (колонка `popularity_status`, которую мы создали ранее). Выведите топ-5 таких исполнителей.

In [75]:
ds = df[df['popularity_status'] == 'Hit']
ds.groupby('track_artist')['popularity_status'].count().sort_values(ascending=False).head()

##тож самое другим путем
df[df['popularity_status'] == 'Hit'].groupby('track_artist')['popularity_status'].count().sort_values(ascending=False).head()

track_artist
Ed Sheeran       37
Billie Eilish    31
Post Malone      28
Selena Gomez     26
Travis Scott     26
Name: popularity_status, dtype: int64

На этом первый семинар завершен! Вы научились загружать данные, делать базовые фильтрации, группировки и исследовать датасет.